name: 'Test Action'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Say Hello with Python Version
      shell: bash
      run: echo "Hello there user, you are using python version ${{ inputs.python-version }}"
    - name: Set GitHub Path
      shell: bash
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
