name: 'Test Action'
inputs:
  python-version:
    required: true
runs:
  using: "composite"
  steps:
    - name: Say Hello with Python Version
      run: echo "Hello there user, you are using python version ${{ inputs.python-version }}"
      shell: bash
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
